version: 0.2
phases:
    build:
        commands:
            - docker build -t oov-app .
            - docker tag oov-app:latest 792228772972.dkr.ecr.eu-central-1.amazonaws.com/oov-app:latest
            - docker push 792228772972.dkr.ecr.eu-central-1.amazonaws.com/oov-app:latest
