version: 0.2
phases:
    build:
        commands:
            - docker build -t oov-app --output type=local,dest=./docker-out .
            - for d in ./*;do [[ -d "$d" ]] && echo "$d" >> tree.txt; done
artifacts:
    files:
        - "tree.txt"
        # - "docker-out/**/*"
