version: 0.2
phases:
    build:
        commands:
            - docker build -t oov-app .
            - docker save oov-app:lates | gzip > oov-app.tar.gz
artifacts:
    files:
        - "oov-app.tar.gz"
