version: 0.2
phases:
    build:
        commands:
            - docker build -t oov-app --output type=local,dest=./docker-out .
            - tree . > tree.txt
artifacts:
    files:
        - "tree.txt"
        # - "docker-out/**/*"
