version: 0.2
phases:
    pre_build:
        commands:
            - REGION=eu-central-1
            - BASE_URI=public.ecr.aws/b2g2z1d1
            - REPOSITORY_URI=$BASE_URI/oov
    build:
        commands:
            - docker build -t oov .
            - docker tag oov:latest $REPOSITORY_URI:latest
    post_build:
        commands:
            - aws ecr-public get-login-password --region $REGION | docker login --username AWS --password-stdin $BASE_URI
            - docker push $REPOSITORY_URI:latest
