version: 0.2
phases:
    pre_build:
        commands:
            - echo Logging into Amazon ECR
            - aws --version
            - ACCOUNT_ID=792228772972
            - REGION=eu-central-1
            - BASE_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
            - REPOSITORY_URI=792228772972.dkr.ecr.eu-central-1.amazonaws.com/oov-ecr
    build:
        commands:
            - echo Build Docker Image
            - docker build -t $REPOSITORY_URI:latest .
    post_build:
        commands:
            - echo Pushing to registry
            - aws ecr get-login-password --region=$REGION | docker login --username AWS --password-stdin $BASE_URI
            - docker push $REPOSITORY_URI:latest
